In [50]:
import pandas as pd

top300 = pd.read_csv('..\\data\\movie_data\\movie_resize_ranking.csv', encoding='utf-8')
top300 = top300[['영화명','개봉일']]

In [52]:
year_df = pd.DataFrame()
for row in top300['개봉일']:
    year_df = pd.concat([year_df, pd.DataFrame([row.split('-')[0]])])

year_df.columns = ['연도']

year_df.index = range(len(top300))

top300 = pd.concat([top300, year_df], axis=1).drop('')
top300

                  영화명         개봉일    연도
0           아바타: 물의 길  2022-12-14  2022
1    어벤져스: 에이지 오브 울트론  2015-04-23  2015
2                 기생충  2019-05-30  2019
3                겨울왕국  2014-01-16  2014
4               인터스텔라  2014-11-06  2014
..                ...         ...   ...
295             테이큰 2  2012-09-27  2012
296                하녀  2010-05-13  2010
297     메이즈 러너: 데스 큐어  2018-01-17  2018
298   분노의 질주: 더 얼티메이트  2021-05-19  2021
299            맘마미아!2  2018-08-08  2018

[300 rows x 3 columns]

In [48]:
top300[top300.duplicated()==True]

        영화명
59     숨바꼭질
60     숨바꼭질
79   미녀와 야수
80   미녀와 야수
81   미녀와 야수
82   미녀와 야수
83   미녀와 야수
84   미녀와 야수
85   미녀와 야수
86   미녀와 야수
87   미녀와 야수
161      귀향
162      귀향
168     스파이
169     스파이
170     스파이
171     스파이
172     스파이
188      영웅
189      영웅
194      마녀
267     정글북
281     히트맨
282     히트맨
290    블라인드

In [51]:
code = pd.read_csv('..\\data\\movie_data\\concat.csv', encoding='utf-8')
code = code[['영화명','네이버URL','연도']]

In [10]:
url_code = []
for i in code['네이버URL']:
    url_code.append(i.split('=')[-1])
print(url_code)

['93756', '167651', '85579', '102875', '136900', '136873', '62266', '115977', '39841', '78726', '94775', '121048', '192608', '163788', '83893', '39894', '167697', '146469', '36666', '130966', '45321', '101901', '136315', '34501', '74977', '98438', '161967', '100931', '45290', '156464', '130903', '174903', '93728', '70254', '62328', '122527', '107924', '102817', '47385', '39569', '187940', '51143', '81888', '173123', '39405', '142384', '70241', '100647', '53372', '208077', '68052', '137952', '83084', '61521', '76016', '58018', '194196', '135874', '158191', '89218', '145162', '141104', '72363', '121788', '142822', '201641', '92575', '121051', '161242', '57723', '65674', '88253', '39157', '146506', '154222', '72054', '71509', '121922', '48227', '95541', '114249', '41450', '102272', '31796', '52515', '89755', '182016', '132623', '43153', '154285', '153652', '41438', '102824', '94767', '99794', '67786', '52548', '98146', '49727', '144330', '125459', '120157', '163533', '137326', '80866', '100691', '167638', '167613', '51777', '31795', '83250', '39436', '136872', '68695', '158178', '73411', '151153', '153687', '115622', '43679', '149747', '43157', '86888', '129049', '134898', '66823', '130013', '76080', '178526', '99752', '176306', '169637', '82540', '130850', '90589', '62262', '115642', '75413', '43678', '62422', '89606', '177909', '132933', '66520', '66381', '88225', '49008', '155665', '47528', '189069', '195758', '44885', '99714', '68217', '123519', '38097', '94187', '34521', '93028', '88426', '39625', '66569', '51082', '62586', '35778', '83268', '65991', '152385', '99740', '67769', '33930', '97692', '96327', '39482', '91073', '119428', '41705', '123596', '37742', '108225', '77768', '150637', '185917', '149236', '45232', '167105', '164192', '63824', '120160', '179482', '182355', '140731', '38766', '223800', '150198', '37883', '192150', '118917', '134963', '135843', '76460', '107373', '39892', '151728', '31464', '57095', '57729', '87571', '82080', '158180', '52326', '101966', '163608', '51386', '40133', '75173', '92075', '177967', '40041', '222301', '132626', '75426', '183876', '34519', '161850', '100072', '36944', '184509', '109905', '69956', '47370', '39786', '175322', '37926', '36720', '36720', '36720', '159892', '36732', '61698', '54411', '51443', '75355', '72522', '37245', '35099', '113344', '39422', '49483', '39654', '82473', '184311', '123277', '95873', '62167', '45919', '136990', '39640', '223016', '37758', '95503', '67900', '78851', '76020', '142803', '103271', '47384', '50869', '184318', '172425', '74315', '119430', '146517', '58072', '50669', '182205', '75401', '38254', '66834', '122120', '43838', '92064', '191646', '97816', '140652', '68073', '167699', '105015', '67901', '196367', '109911', '146480', '80629', '52747', '61103', '129408', '127398', '73318', '68944', '78790', '92011', '129383', '187347', '50184', '45979', '172454', '103535', '137890', '77566', '124201', '113351', '89361', '123630', '144968', '70457', '168298', '97629', '77125', '44913', '52375', '43547', '146524', '38662', '117790', '86867', '39818', '76347', '122489', '35546', '38197', '134980', '177374', '127382', '39907', '31281', '38384', '41363', '36727', '91045', '189053', '129094', '53741', '93090', '40134', '165748', '149512', '154255', '167605', '185838', '167099', '75395', '98467', '47152', '70994', '35071', '63538', '79557', '155716', '55677', '33837', '39652', '36719', '49525', '47531', '118950', '118950', '130849', '91510', '71920', '149248', '189150', '55405', '164115', '74566', '40033', '191634', '92823', '69940', '47421', '45292', '109960', '136898', '36825', '77128', '12954', '73508', '59845', '48246', '96951', '52552', '51132', '65610', '37397', '41585', '39378', '188472', '122535', '103760', '65540', '37919', '50163', '68196', '69986', '125473', '73344', '51076', '196051', '179159', '71628', '156083', '113312', '37853', '187323', '60753', '139700', '184516', '71499', '43537', '43995', '62219', '162981', '98484', '147001', '75724', '83546', '100990', '117787', '43368', '67785', '129050', '59075', '143394', '36956', '184517', '50932', '134895', '184519', '93933', '37148', '124212', '39369', '67374', '50621', '181381', '190010', '38619', '187322', '204640', '37380', '107960', '164106', '66728', '51918', '61503', '152341', '114282', '97826', '51407', '39379', '49480', '184509', '184509', '189537', '164172', '126032', '198413', '74027', '73477', '36843', '58088', '69958', '72962', '61101', '96959', '157297', '109982', '52495', '81891', '72405', '162173', '96961', '72408', '62290', '39708', '164173', '44019', '90885', '99701', '180351', '45921', '68063', '36955', '188909', '91696', '45416', '116866', '35628', '38420', '66091', '40177', '175324', '116234', '127496', '75475', '152632', '58085', '113348', '187348', '89636', '39863', '128235', '60484', '144938', '39399', '68435', '30301', '152625', '184513', '87566', '183866', '75396', '90596', '85640', '48747', '152656', '119966', '64185', '34190', '69989', '39756', '57865', '37261', '127397', '64994', '105521', '144927', '37461', '166092', '114276', '82227', '85855', '185614', '144280', '48598', '38421', '86381', '174065', '72058', '74632', '39909', '65649', '68046', '106522', '81128', '116532', '62638', '178544', '159866', '74565', '160487', '65994', '134982', '174835', '91192', '39675', '87309', '44477', '65669', '35991', '189141', '61115', '34533', '69207', '119632', '164139', '41350', '62566', '89873', '191559', '171755', '193194', '44529', '192151', '51306', '38466', '44008', '186821', '66464', '85633', '122596', '37725', '113377', '76048', '109193', '154449', '74866', '35110', '39510', '66463', '38908', '66143', '124041', '164101', '160749', '109753', '74567', '38906', '94506', '36343', '43206', '34486', '88461', '167635', '113353', '175366', '66363', '181692', '79102', '38408', '115504', '190320', '65541', '52234', '48742', '106360', '45944', '125468', '92003', '52541', '36931', '160399', '158112', '57758', '38510', '162249', '38883', '164932', '193855', '110332', '152170', '39846', '40096', '146485', '107928', '181710', '47229', '88252', '88295', '47036', '141206', '194204', '38835', '153675', '75397', '109910', '118377', '52516', '69105', '165026', '97857', '92471', '68437', '99715', '63722', '36699', '137696', '64247', '64161', '64126', '63150', '32116', '143245', '50672', '82428', '37908', '39516', '60311', '61639', '181925', '65463', '37869', '40098', '196854', '46869', '88489', '179158', '38452', '56227', '38091', '73114', '38888', '76691', '99702', '182234', '73317', '130720', '107923', '64920', '85702', '38488', '104612', '180025', '53751', '56247', '155256', '51018', '98970', '37838', '39715', '124025', '61060', '72560', '137875', '96917', '58280', '164122', '39448', '39364', '36858', '49532', '112079', '175316', '13092', '69467', '187821', '92047', '145292', '134899', '35878', '84189', '39639', '75006', '120125', '96969', '113342', '182360', '125414', '36798', '142625', '81010', '180390', '52420', '39427', '159806', '97693', '187310', '74893', '152168', '94170', '169347', '66440', '129051', '66358', '45664', '83017', '180374', '62789', '144918', '85659', '120123', '29824', '65769', '118958', '70397', '220733', '65429', '179125', '42117', '73301', '37770', '125494', '87308', '72270', '44923', '35892', '169643', '36755', '136686', '40222', '50681', '140718', '79439', '13838', '187349', '53941', '65021', '45253', '134960', '95515', '73339', '74147', '45129', '39440', '71498', '159893', '129095', '82219', '65893', '34229', '47414', '45802', '40323', '53813', '136868', '36835', '49728', '65090', '52553', '168049', '69689', '181698', '160375', '38323', '144944', '65724', '62560', '153651', '41399', '72648', '99797', '84897', '129406', '40135', '82142', '66026', '84899', '68616', '78720', '35623', '96325', '133129', '121090', '85870', '77017', '39576', '125488', '173668', '83095', '73418', '186615', '112268', '57899', '93089', '194205', '49475', '154112', '44920', '65058', '70427', '37243', '66215', '97858', '79435', '60166', '37038', '137915', '37930', '101242', '127338', '191597', '92176', '36837', '42846', '136835', '37439', '118967', '87307', '36790', '51700', '46494', '52551', '43396', '116251', '118955', '65840', '205027', '88453', '210852', '154282', '109906', '35282', '180378', '189046', '82799', '24944', '37236', '154668', '87305', '187320', '37262', '47494', '74309', '175727', '76692', '76581', '72523', '85857', '187321', '75415', '87216', '82906', '154272', '189368', '164125', '37738', '186613', '120791', '65995', '34195', '122916', '100644', '64129', '66144', '97631', '136893', '38850', '36728', '37888', '219812', '149221', '86784', '49216', '37929', '204496', '79105', '37716', '167100', '215466', '122984', '39769', '114286', '169349', '93715', '143402', '143456', '182362', '164907', '43209', '70995', '39360', '189000', '114225', '39622', '49835', '70469', '39809', '100643', '76439', '67075', '100950', '37710', '118922', '190726', '38449', '50598', '74904', '117774', '38899', '90834', '36778', '190694', '39849', '39849', '60016', '177366', '109116', '97612', '72562', '43510', '92046', '172010', '39441', '183136', '159877', '89294', '110333', '37246', '134838', '65532', '103324', '65808', '146512', '47411', '185933', '118370', '39906', '51959', '41672', '57675', '68086', '191430', '44910', '127865', '93727', '80737', '61184', '45889', '62894', '50407', '37266', '51781', '171725', '132996', '61450', '155356', '36589', '38378', '101963', '38881', '199860', '79159', '181114', '100987', '41586', '73096', '10153', '67195', '62838', '191637', '141824', '61845', '70910', '32680', '39624', '104816', '37880', '68334', '78161', '41340', '129461', '167657', '47587', '71987', '67366', '125421', '133457', '190400', '57805', '65963', '174805', '40034', '50667', '79140', '37354', '116233', '58273', '168058', '36799', '53041', '213733', '65245', '200745', '37739', '52504', '60015', '60015', '76051', '140649', '47987', '128258', '76445', '89723', '62285', '49852', '69917', '72007', '40194', '143473', '56058', '136899', '67533', '76455', '175324', '41627', '85094', '70121', '51786', '37938', '52593', '65473', '167653', '79566', '124031', '103759', '61506', '210282', '51124', '47506', '176670', '130786', '31488', '75216', '143495', '179181', '70637', '82924', '65535', '81106', '38738', '129783', '76972', '54974', '136007', '36025', '119412', '80664', '39626', '125484', '195973', '46875', '79312', '66471', '196809', '74879', '89630', '39442', '177509', '38277', '37837', '100930', '73394', '107961', '82434', '77821', '63562', '66818', '61273', '61025', '118909', '79559', '109937', '167560', '65845', '152616', '187366', '95333', '62699', '66729', '42596', '65869', '74269', '52744', '86899', '69299', '50368', '114265', '101700', '84218', '181554', '189001', '116254', '84216', '56038', '78331', '37686', '84843', '95877', '37049', '44625', '180425', '68537', '85906', '42589', '118931', '146560', '67733', '83741', '53825', '68952', '158647', '187629', '127378', '69776', '36678', '150688', '130987', '134845', '180379', '37235', '45529', '36734', '76960', '163834', '37383', '40102', '56083', '34569', '38618', '62550', '72177', '173653', '66754', '158601', '35973', '38855', '90597', '175393', '52992', '32630', '159037', '160491', '66002', '49336', '92533', '37073', '42690', '190991', '39411', '155263', '74736', '85578', '152661', '75471', '222965', '168011', '92412', '66189', '72042', '57971', '37969', '123470', '93158', '149777', '65113', '158622', '185264', '64686', '46314', '134873', '76348', '54563', '159887', '118953', '137970', '88495', '141259', '58023', '38880', '52307', '70999', '165722', '39706', '57335', '149049', '144694', '93035', '158626', '127901', '187161', '63845', '126034', '57950', '67294', '35297', '90901', '90674', '92526', '104494', '75400', '168050', '217719', '168023', '215970', '100654', '54704', '152396', '153642', '66402', '120165', '33259', '44044', '183850', '132998', '120513', '93739', '38574', '71932', '76651', '41375', '63916', '136821', '102278', '62265', '190695', '164151', '103381', '91703', '77039', '36676', '82188', '190377', '52144', '134136', '61699', '45976', '137008', '36992', '71790', '83098', '31479', '163826', '118974', '80628', '40321', '159830', '175318', '112041', '76450', '45938', '47381', '42842', '86862', '58004', '70434', '38547', '166610', '163933', '211161', '45298', '103762', '152156', '43208', '172780', '39471', '82389', '147092', '159054', '73638', '213481', '189124', '136842', '71073', '155411', '143253', '94195', '79826', '81935', '65723', '51856', '186233', '76667', '50317', '36835', '52072', '40035', '66583', '62960', '171752', '49692', '66283', '61535', '142699', '37101', '58288', '223799', '164143', '68563', '98149', '171539', '155484', '45118', '81315', '76377', '120141', '38699', '74528', '180381', '118966', '38722', '43210', '89667', '33379', '41754', '110652', '81316', '39479', '103222', '64195', '36341', '57598', '167569', '187351', '159812', '159805', '214552', '44911', '40887', '181411', '127374', '191657', '61056', '124042', '180372', '144379', '121052', '100926', '62742', '39601', '142691', '53084', '116799', '187893', '137945', '46532', '187350', '37642', '93931', '118968', '201642', '192620', '51943', '183862', '77919', '43681', '163844', '36565', '123420', '61701', '51871', '173019', '160892', '43568', '35999', '65213', '69023', '196047', '40112', '44006', '154226', '92068', '54977', '172764', '100828', '65721', '100015', '159074', '204624', '47401', '144943', '86507', '38923', '67513', '152331', '94897', '72357', '66438', '70651', '154353', '80465', '39853', '53097', '57968', '71942', '38882', '74303', '202903', '37376', '57994', '156675', '77154', '61485', '34570', '69858', '115303', '73787', '219402', '76451', '36583', '43536', '45942', '57897', '71081', '86129', '137327', '68204', '68050', '134856', '112039', '39908', '36743', '118307', '172975', '37740', '37759', '52453', '127346', '84065', '74610', '42792', '146459', '179859', '86866', '65433', '96377', '66803', '155715', '130787', '75217', '225700', '210289', '163787', '76955', '109984', '214603', '70118', '209280', '180220', '27103', '105246', '43516', '189075', '38620', '92576', '51083', '42845', '52245', '187051', '46985', '146489', '93005', '38573', '56225', '96986', '216100', '156477', '185293', '95501', '118952', '35998', '140647', '96326', '137884', '38414', '118364', '54565', '42858', '43508', '80626', '102648', '143416', '195983', '45535', '56252', '125841', '140010', '140696', '164200', '45285', '65064', '184357', '62342', '143435', '184518', '88227', '53350', '115520', '109466', '144945', '39878', '36736', '140139', '165025', '58252', '71487', '124013', '156047', '79762', '49228', '69099', '65842', '58255', '119456', '136872', '119456', '136872', '101962', '73412', '66510', '212095', '176354', '71139', '65020', '64192', '190324', '65067', '57488', '114146', '44922', '164183', '53351', '99096', '191914', '136687', '53159', '73918', '95769', '208530', '154667', '112040', '183110', '114248', '38281', '58287', '36351', '35990', '45491', '53609', '137010', '38364', '85671', '89724', '88477', '88270', '127866', '84034', '57718', '87716', '62896', '122473', '86347', '38227', '57278', '92067', '36839', '35626', '52103', '107370', '87314', '65597', '69952', '67883', '39470', '113301', '118903', '58387', '53025', '183836', '177483', '145335', '62626', '43844', '180209', '68880', '152249', '43493', '36945', '181959', '43612', '144266', '69102', '190722', '85842', '78294', '119452', '42253', '73285', '38341', '149645', '109955', '172836', '52524', '143932', '76627', '57570', '68798', '37493', '191434', '97854', '65340', '153964', '173692', '68169', '90553', '68038', '61104', '50682', '82081', '100801', '156496', '65435', '64093', '78160', '60618', '100938', '38451', '80707', '64154', '118365', '97856', '37355', '101960', '68060', '64995', '74485', '167602', '55688', '39911', '65642', '153580', '129333', '151196', '87311', '165461', '65968', '50185', '130765', '133380', '74799', '72043', '104478', '76369', '169078', '39506', '39614', '41242', '57661', '39804', '35165', '98997', '50278', '101972', '52413', '179406', '39474', '125802', '189260', '66025', '49004', '217035', '62174', '122457', '54435', '50704', '61632', '30689', '70908', '68707', '47339', '74621', '94829', '66725', '38824', '60486', '68434', '97696', '64273', '225808', '123050', '168017', '69798', '84414', '57412', '142317', '125405', '51158', '39393', '40743', '61963', '94133', '36841', '204649', '78218', '167491', '99094', '32115', '103343', '137908', '38338', '100935', '127328', '133447', '86023', '190381', '51807', '191547', '47364', '65735', '221031', '203097', '73478', '76458', '224929', '152680', '139674', '49463', '153620', '32972', '100610', '219834', '45521', '68587', '132380', '65515', '204214', '163663', '107992', '65296', '119914', '45749', '95531', '45113', '87232', '134134', '208508', '99724', '31563', '151151', '36373', '31574', '168037', '62556', '35937', '191548', '35903', '72044', '70000', '34532', '79565', '67696', '56447', '117861', '76444', '37899', '51957', '127768', '133223', '182001', '51947', '149504', '154598', '83731', '172003', '93002', '71769', '193804', '60548', '146214', '65242', '69990', '35314', '52487', '222543', '153951', '67061', '156200', '164155', '158631', '66602', '136876', '144693', '200894', '191600', '48310', '64242', '36953', '65738', '36959', '140693', '199393', '121047', '118408', '67768', '69742', '49857', '140656', '73018', '92599', '53000', '68035', '190395', '76456', '65109', '45709', '118409', '94190', '90388', '164200', '33175', '183122', '102309', '100205', '46330', '180399', '137281', '52972', '39758', '179875', '36846', '39862', '73193', '72359', '57178', '205968', '219764', '154672', '47048', '61023', '34520', '43610', '158885', '180169', '38799', '187311', '214665', '45695', '42157', '30076', '83410', '50498', '99748', '152344', '61095', '57684', '49725', '36505', '19303', '213903', '172187', '81478', '152183', '40122', '94112', '66625', '71623', '99800', '159862', '84631', '56473', '118348', '125426', '165287', '68269', '174626', '144081', '65091', '121061', '50580', '167599', '100203', '180384', '66253', '127363', '119431', '179894', '77117', '50610', '34045', '127375', '168092', '35941', '161984', '91606', '68291', '48159', '172118', '52555', '76454', '48238', '163831', '65542', '49945', '95876', '101430', '37244', '84917', '72327', '62233', '129012', '36865', '39512', '69339', '37050', '191143', '55872', '219836', '142305', '54975', '68945', '152684', '35175', '65068', '38615', '162932', '44982', '157178', '99738', '133496', '175404', '168727', '39484', '62562', '92069', '62272', '172174', '69991', '200785', '54254', '109200', '43520', '159070', '37757', '40208', '218816', '190374', '47101', '127335', '158910', '104426', '74425', '44864', '44864', '36337', '38081', '136824', '190382', '148655', '94766', '49726', '61658', '78784', '32620', '174834', '153279', '122581', '92584', '36055', '52777', '86505', '34972', '56469', '53781', '148909', '209274', '78388', '54290', '57486', '38739', '82253', '117802', '38318', '130978', '52545', '209496', '143372', '62733', '37408', '51775', '196362', '170496', '47407', '66195', '77147', '54678', '51510', '52525', '144215', '125439', '65092', '132989', '168047', '61700', '33095', '70992', '102639', '68333', '82487', '185282', '38582', '42841', '62694', '214637', '191633', '125466', '98485', '109920', '37150', '98404', '152169', '65093', '45280', '144226', '45397', '37464', '40064', '120788', '142272', '197304', '43502', '152161', '34309', '120102', '62331', '66724', '132627', '42462', '137709', '42584', '45475', '163811', '122195', '71943', '53158', '40163', '49007', '39043', '33101', '55682', '140265', '76461', '49529', '82432', '218056', '200892', '99354', '174830', '93929', '127321', '114277', '67562', '161847', '113170', '224788', '31867', '134135', '158555', '115512', '183803', '91603', '53152', '

In [29]:
code2 =pd.DataFrame([url_code]).transpose()
code2.columns = ['url_code']
code2

     url_code
0       93756
1      167651
2       85579
3      102875
4      136900
...       ...
4434   118943
4435    78188
4436    44310
4437   171467
4438    41589

[4439 rows x 1 columns]

In [40]:
code3 = pd.concat([code, code2],axis=1)
code3.drop_duplicates(['영화명'], keep='first', inplace=True)
code3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4384 entries, 0 to 4438
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   영화명       4384 non-null   object
 1   네이버URL    4384 non-null   object
 2   url_code  4384 non-null   object
dtypes: object(3)
memory usage: 137.0+ KB

In [6]:
top300.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화명     300 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB

In [41]:
merged_code = pd.merge(top300, code3[['영화명','url_code']], on='영화명')
merged_code.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   영화명       300 non-null    object
 1   url_code  300 non-null    object
dtypes: object(2)
memory usage: 7.0+ KB

In [43]:
merged_code.to_csv('movie_code_utf8.csv', encoding='utf-8')

In [44]:
merged_code

                  영화명 url_code
0           아바타: 물의 길    74977
1    어벤져스: 에이지 오브 울트론    98438
2                 기생충   161967
3                겨울왕국   100931
4               인터스텔라    45290
..                ...      ...
295             테이큰 2    91510
296                하녀    71920
297     메이즈 러너: 데스 큐어   149248
298   분노의 질주: 더 얼티메이트   189150
299            맘마미아!2   164115

[300 rows x 2 columns]