### pip install & import

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
#import pandas_profiling
import datetime

# 크롤링 데이터 merge

### resize된 데이터 불러오기

In [3]:
movie_resize_ALL = pd.read_csv('../2_resizing/resizing_all.csv',encoding='utf-8')
movie_resize_회귀 = pd.read_csv('../2_resizing/resizing_reg.csv',encoding='utf-8')
movie_resize_분류 = pd.read_csv('../2_resizing/resizing_cls.csv',encoding='utf-8')

### 크롤링 파일 불러오기

In [4]:
# concat.csv에서 '평점'과 '출연'만 가져오기
df2 = pd.read_csv("/Users/yoojunghyun/Desktop/WebProj/MovieDL/data/movie_data/concat.csv", encoding='UTF-8',index_col=0) # ../../data/movie_data/concat.csv
df2 = df2.drop(['네이버URL','이미지URL','제작연도','감독','연도'],axis=1)

### 빈칸 있는 데이터 삭제

In [5]:
# null 값이 있는 열 삭제 
df2 = df2[df2['출연'].isnull() == False] 
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4331 entries, 0 to 4834
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화명     4331 non-null   object
 1   출연      4331 non-null   object
 2   평점      4331 non-null   float64
dtypes: float64(1), object(2)
memory usage: 135.3+ KB

### movie_resize 파일과 크롤링 파일 merge

In [6]:
# '영화명'을 기준으로 데이터 합치기
movie_resize4 = pd.merge(movie_resize_ALL,df2,on='영화명')
movie_resize5 = pd.merge(movie_resize_회귀,df2,on='영화명')
movie_resize6 = pd.merge(movie_resize_분류,df2,on='영화명')

### 중복 데이터 삭제 후 movie_resize_merged_ .csv 생성

In [7]:
# '영화명'을 기준으로 중복되는 행의 첫번째 값은 두고 나머지를 삭제
movie_resize4.drop_duplicates('영화명',keep='first',inplace=True)
movie_resize4.info()

movie_resize5.drop_duplicates('영화명',keep='first',inplace=True)
movie_resize5.info()

movie_resize6.drop_duplicates('영화명',keep='first',inplace=True)
movie_resize6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3125 entries, 0 to 3229
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  3125 non-null   int64
 1   순번          3125 non-null   int64
 2   영화명         3125 non-null   object
 3   감독          3125 non-null   object
 4   배급사         3125 non-null   object
 5   개봉일         3125 non-null   object
 6   영화형태        3125 non-null   object
 7   국적          3125 non-null   object
 8   전국 스크린수     3125 non-null   int64
 9   전국 매출액      3125 non-null   int64
 10  전국 관객수      3125 non-null   int64
 11  서울 매출액      3125 non-null   object
 12  서울 관객수      3125 non-null   object
 13  장르          3125 non-null   object
 14  등급          3125 non-null   object
 15  영화구분        3125 non-null   object
 16  연도          3125 non-null   int64
 17  월           3125 non-null   int64
 18  계절          3125 non-null   object
 19  총 관객수       3125 non-null   int64
 20  코로나         3125 non-null   int64
 21  출연          3125 non-null   object
 22  평점          3125 non-null   float64
dtypes: float64(1), int64(9), object(13)
memory usage: 585.9+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1413 entries, 0 to 1449
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1413 non-null   int64
 1   순번          1413 non-null   int64
 2   영화명         1413 non-null   object
 3   감독          1413 non-null   object
 4   배급사         1413 non-null   object
 5   개봉일         1413 non-null   object
 6   영화형태        1413 non-null   object
 7   국적          1413 non-null   object
 8   전국 스크린수     1413 non-null   int64
 9   전국 매출액      1413 non-null   int64
 10  전국 관객수      1413 non-null   int64
 11  서울 매출액      1413 non-null   object
 12  서울 관객수      1413 non-null   object
 13  장르          1413 non-null   object
 14  등급          1413 non-null   object
 15  영화구분        1413 non-null   object
 16  연도          1413 non-null   int64
 17  월           1413 non-null   int64
 18  계절          1413 non-null   object
 19  총 관객수       1413 non-null   int64
 20  코로나         1413 non-null   int64
 21  출연          1413 non-null   object
 22  평점          1413 non-null   float64
dtypes: float64(1), int64(9), object(13)
memory usage: 264.9+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 708 entries, 0 to 727
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  708 non-null    int64
 1   순번          708 non-null    int64
 2   영화명         708 non-null    object
 3   감독          708 non-null    object
 4   배급사         708 non-null    object
 5   개봉일         708 non-null    object
 6   영화형태        708 non-null    object
 7   국적          708 non-null    object
 8   전국 스크린수     708 non-null    int64
 9   전국 매출액      708 non-null    int64
 10  전국 관객수      708 non-null    int64
 11  서울 매출액      708 non-null    object
 12  서울 관객수      708 non-null    object
 13  장르          708 non-null    object
 14  등급          708 non-null    object
 15  영화구분        708 non-null    object
 16  연도          708 non-null    int64
 17  월           708 non-null    int64
 18  계절          708 non-null    object
 19  총 관객수       708 non-null    int64
 20  코로나         708 non-null    int64
 21  출연          708 non-null    object
 22  평점          708 non-null    float64
dtypes: float64(1), int64(9), object(13)
memory usage: 132.8+ KB

In [8]:
# Unnamed: 0 삭제하는 법
# drop 할 때에는 list에 넣어서 한다.

movie_resize4.drop(['Unnamed: 0'],axis=1,inplace=True)
movie_resize5.drop(['Unnamed: 0'],axis=1,inplace=True)
movie_resize6.drop(['Unnamed: 0'],axis=1,inplace=True)

In [9]:
# 중복 데이터 없어졌는 지 확인
movie_resize4[movie_resize4.duplicated()==True]
movie_resize5[movie_resize5.duplicated()==True]
movie_resize6[movie_resize6.duplicated()==True]

Empty DataFrame
Columns: [순번, 영화명, 감독, 배급사, 개봉일, 영화형태, 국적, 전국 스크린수, 전국 매출액, 전국 관객수, 서울 매출액, 서울 관객수, 장르, 등급, 영화구분, 연도, 월, 계절, 총 관객수, 코로나, 출연, 평점]
Index: []

[0 rows x 22 columns]

In [10]:
# 변경 될때만 따로 풀어서 사용하시길.(파일생성코드)
movie_resize4.to_csv('./movie_resize_merged_all.csv',encoding='utf-8')
movie_resize5.to_csv('./movie_resize_merged_reg.csv',encoding='utf-8')
movie_resize6.to_csv('./movie_resize_merged_cls.csv',encoding='utf-8')

# Top 300 생성

### merge된 데이터 불러오기

In [14]:
movie_resize_all = pd.read_csv('./movie_resize_merged_all.csv',encoding='utf-8')

### movie_resize_ranking.csv 생성

In [12]:
# 변경 될때만 따로 풀어서 사용하시길.(파일생성코드)
col = ['영화명', '감독', '배급사', '개봉일', '출연']
movie_resize_all.reset_index(drop=False,inplace=True)
movie_resize_all[col][:300].to_csv(
    './movie_resize_ranking.csv', encoding="utf-8")

In [13]:
# movie_resize_ranking.csv 불러와서 ['개봉일'] datetime으로 타입변경
movie_resize_ranking = pd.read_csv('./movie_resize_ranking.csv',encoding='UTF-8')
movie_resize_ranking['개봉일'] = movie_resize_ranking['개봉일'].astype('datetime64')
movie_resize_ranking.drop(['Unnamed: 0'], axis=1, inplace=True)
movie_resize_ranking

,영화명,감독,배급사,개봉일,출연
0,명량,김한민,씨제이이엔엠,2014-07-30,"['최민식', '류승룡', '조진웅']"
1,극한직업,이병헌,씨제이이엔엠,2019-01-23,"['류승룡', '이하늬', '진선규', '이동휘', '공명']"
2,신과함께-죄와 벌,김용화,롯데엔터테인먼트,2017-12-20,"['하정우', '차태현', '주지훈', '김향기', '김동욱', '마동석']"
3,국제시장,윤제균,씨제이이엔엠,2014-12-17,"['황정민', '김윤진', '오달수', '정진영']"
4,어벤져스: 엔드게임,안소니 루소,월트디즈니스튜디오스코리아,2019-04-24,"['로버트 다우니 주니어', '크리스 에반스', '크리스 헴스워스', '마크 러팔로..."
...,...,...,...,...,...
295,호빗: 스마우그의 폐허,피터 잭슨,워너브러더스 코리아,2013-12-12,"['휴고 위빙', '마틴 프리먼', '루크 에반스', '베네딕트 컴버배치', '이안..."
296,미니언즈2,카일 발다,유니버설픽쳐스인터내셔널 코리아,2022-07-20,"['스티브 카렐', '타라지 P. 헨슨', '루시 로리스', '장 끌로드 반담', ..."
297,컨저링,제임스 완,워너브러더스 코리아,2013-09-17,"['베라 파미가', '매켄지 포이', '패트릭 윌슨', '조이 킹', '릴리 테일러..."
298,슈렉 포에버,마이크 미첼,씨제이이엔엠,2010-07-01,"['마이크 마이어스', '에디 머피', '카메론 디아즈', '안토니오 반데라스']"
299,이글 아이,D.J. 카루소,씨제이이엔엠,2008-10-09,"['샤이아 라보프', '미셸 모나한']"

# 특정 독립변수 추가 및 점수화

### merge된 데이터 불러오기

In [15]:
movie_resize_all = pd.read_csv('./movie_resize_merged_all.csv',encoding='utf-8')
movie_resize5.to_csv('./movie_resize_merged_reg.csv',encoding='utf-8')
movie_resize6.to_csv('./movie_resize_merged_cls.csv',encoding='utf-8')

### 점수화행 만들기

In [16]:
# 점수화행 만들기
movie_resize_회귀['개봉일'] = movie_resize_회귀['개봉일'].astype('datetime64')

movie_final_회귀 = movie_resize_회귀.copy()
movie_final_회귀['감독_흥행'] = [0 for _ in range(len(movie_resize_회귀))]
movie_final_회귀['배급사_흥행'] = [0 for _ in range(len(movie_resize_회귀))]
movie_final_회귀['주연배우_흥행'] = [0 for _ in range(len(movie_resize_회귀))]

In [17]:
# 점수화행 만들기
movie_resize_분류['개봉일'] = movie_resize_분류['개봉일'].astype('datetime64')

movie_final_분류 = movie_resize_분류.copy()
movie_final_분류['감독_흥행'] = [0 for _ in range(len(movie_resize_분류))]
movie_final_분류['배급사_흥행'] = [0 for _ in range(len(movie_resize_분류))]
movie_final_분류['주연배우_흥행'] = [0 for _ in range(len(movie_resize_분류))]

In [19]:
# 순번을 쓰기 위해 인덱스 풀기

movie_resize_ranking.reset_index(drop=False,inplace=True)
movie_resize_ranking

,level_0,index,영화명,감독,배급사,개봉일,출연
0,0,0,명량,김한민,씨제이이엔엠,2014-07-30,"['최민식', '류승룡', '조진웅']"
1,1,1,극한직업,이병헌,씨제이이엔엠,2019-01-23,"['류승룡', '이하늬', '진선규', '이동휘', '공명']"
2,2,2,신과함께-죄와 벌,김용화,롯데엔터테인먼트,2017-12-20,"['하정우', '차태현', '주지훈', '김향기', '김동욱', '마동석']"
3,3,3,국제시장,윤제균,씨제이이엔엠,2014-12-17,"['황정민', '김윤진', '오달수', '정진영']"
4,4,4,어벤져스: 엔드게임,안소니 루소,월트디즈니스튜디오스코리아,2019-04-24,"['로버트 다우니 주니어', '크리스 에반스', '크리스 헴스워스', '마크 러팔로..."
...,...,...,...,...,...,...,...
295,295,295,호빗: 스마우그의 폐허,피터 잭슨,워너브러더스 코리아,2013-12-12,"['휴고 위빙', '마틴 프리먼', '루크 에반스', '베네딕트 컴버배치', '이안..."
296,296,296,미니언즈2,카일 발다,유니버설픽쳐스인터내셔널 코리아,2022-07-20,"['스티브 카렐', '타라지 P. 헨슨', '루시 로리스', '장 끌로드 반담', ..."
297,297,297,컨저링,제임스 완,워너브러더스 코리아,2013-09-17,"['베라 파미가', '매켄지 포이', '패트릭 윌슨', '조이 킹', '릴리 테일러..."
298,298,298,슈렉 포에버,마이크 미첼,씨제이이엔엠,2010-07-01,"['마이크 마이어스', '에디 머피', '카메론 디아즈', '안토니오 반데라스']"
299,299,299,이글 아이,D.J. 카루소,씨제이이엔엠,2008-10-09,"['샤이아 라보프', '미셸 모나한']"

### 감독, 배급사 점수화 코드

### 회귀 모델 점수화

In [18]:
# 감독 점수화 코드

for idx, row in movie_final_회귀.iterrows():
    # 개봉일 기준
    open = datetime.datetime.strftime(row['개봉일'], '%Y-%m-%d')
    director = row['감독'].strip()
    # Top300 중 개봉일 이전 영화의 감독 확인
    directors = movie_resize_ranking[(movie_resize_ranking['개봉일'] < open) & (movie_resize_ranking['감독'] == director)]
    # 해당 감독이 있다면 흥행 여부 표시
    if len(directors) > 0:
        score = directors.index[0]
        if score >= 271:
            score = 1
        elif score >= 241:
            score = 2
        elif score >= 211:
            score = 3
        elif score >= 181:
            score = 4
        elif score >= 151:
            score = 5
        elif score >= 121:
            score = 6
        elif score >= 91:
            score = 7
        elif score >= 61:
            score = 8
        elif score >= 31:
            score = 9
        else:
            score = 10
        movie_final_회귀.loc[idx, '감독_흥행'] = score

In [19]:
# 배급사 정수화 코드 
for idx, row in movie_final_회귀.iterrows():
    # 개봉일 기준
    open = datetime.datetime.strftime(row['개봉일'], '%Y-%m-%d')
    director = row['배급사'].strip()
    # Top300 중 개봉일 이전 영화의 감독 확인
    directors = movie_resize_ranking[(movie_resize_ranking['개봉일'] < open) & (movie_resize_ranking['배급사'] == director)]
    # 해당 감독이 있다면 흥행 여부 표시
    if len(directors) > 0:
        score = directors.index[0]
        if score >= 271:
            score = 1
        elif score >= 241:
            score = 2
        elif score >= 211:
            score = 3
        elif score >= 181:
            score = 4
        elif score >= 151:
            score = 5
        elif score >= 121:
            score = 6
        elif score >= 91:
            score = 7
        elif score >= 61:
            score = 8
        elif score >= 31:
            score = 9
        else:
            score = 10
        movie_final_회귀.loc[idx, '배급사_흥행'] = score

In [20]:
# 배우의 경우 '["배우1", "배우2"]'와 같은 형태이므로 각 값을 뽑아낸다.
# literal_evel : 문자열 그대로 파이썬 명령을 실행시켜주는 함수
# 예시---------------------------------------
# 문자열 : "['문자열1', '문자열2', 22, '33']"
# 리스트 : ['문자열1', '문자열2', 22, '33']
from ast import literal_eval

for idx, row in movie_final_회귀.iterrows():
    # 개봉일 기준
    open = datetime.datetime.strftime(row['개봉일'], '%Y-%m-%d')
    # 해당 영화의 배우 확인
    this_actors = literal_eval(row['출연'])
    scores = [0] * len(this_actors)
    # 개봉일 이전 영화의 모든 배우 확인
    for i in range(len(this_actors)):
        actors = movie_resize_ranking.query(f'개봉일 < "{open}"')
        actors = actors.query(
            f'출연.str.contains("{this_actors[i]}")', engine='python')
        if len(actors) > 0:
            score = actors.index[0]
            if score >= 271:
                score = 1
            elif score >= 241:
                score = 2
            elif score >= 211:
                score = 3
            elif score >= 181:
                score = 4
            elif score >= 151:
                score = 5
            elif score >= 121:
                score = 6
            elif score >= 91:
                score = 7
            elif score >= 61:
                score = 8
            elif score >= 31:
                score = 9
            else:
                score = 10
            scores[i] = score

    # 평균/합/최대값 중에 잘 나오는 걸로        
    # 평균값
    # movie_final.loc[idx, '주연배우_흥행'] = round(sum(scores) / len(scores), 1)
    # 합
    movie_final_회귀.loc[idx, '주연배우_흥행'] = sum(scores)
    # 최대값
    # movie_final.loc[idx, '주연배우_흥행'] = max(scores)

In [21]:
# 값 확인
print((movie_final_회귀['감독_흥행'] == 0).value_counts())
print()
print((movie_final_회귀['배급사_흥행'] == 0).value_counts())
print()
print((movie_final_회귀['주연배우_흥행'] == 0).value_counts())

True     1363
False      50
Name: 감독_흥행, dtype: int64

True     1025
False     388
Name: 배급사_흥행, dtype: int64

True     921
False    492
Name: 주연배우_흥행, dtype: int64

### 분류 모델 점수화

In [22]:
# 감독 점수화 코드

for idx, row in movie_final_분류.iterrows():
    # 개봉일 기준
    open = datetime.datetime.strftime(row['개봉일'], '%Y-%m-%d')
    director = row['감독'].strip()
    # Top300 중 개봉일 이전 영화의 감독 확인
    directors = movie_resize_ranking[(movie_resize_ranking['개봉일'] < open) & (movie_resize_ranking['감독'] == director)]
    # 해당 감독이 있다면 흥행 여부 표시
    if len(directors) > 0:
        score = directors.index[0]
        if score >= 271:
            score = 1
        elif score >= 241:
            score = 2
        elif score >= 211:
            score = 3
        elif score >= 181:
            score = 4
        elif score >= 151:
            score = 5
        elif score >= 121:
            score = 6
        elif score >= 91:
            score = 7
        elif score >= 61:
            score = 8
        elif score >= 31:
            score = 9
        else:
            score = 10
        movie_final_분류.loc[idx, '감독_흥행'] = score

In [23]:
# 배급사 정수화 코드 
for idx, row in movie_final_분류.iterrows():
    # 개봉일 기준
    open = datetime.datetime.strftime(row['개봉일'], '%Y-%m-%d')
    director = row['배급사'].strip()
    # Top300 중 개봉일 이전 영화의 감독 확인
    directors = movie_resize_ranking[(movie_resize_ranking['개봉일'] < open) & (movie_resize_ranking['배급사'] == director)]
    # 해당 감독이 있다면 흥행 여부 표시
    if len(directors) > 0:
        score = directors.index[0]
        if score >= 271:
            score = 1
        elif score >= 241:
            score = 2
        elif score >= 211:
            score = 3
        elif score >= 181:
            score = 4
        elif score >= 151:
            score = 5
        elif score >= 121:
            score = 6
        elif score >= 91:
            score = 7
        elif score >= 61:
            score = 8
        elif score >= 31:
            score = 9
        else:
            score = 10
        movie_final_분류.loc[idx, '배급사_흥행'] = score

In [24]:
# 배우의 경우 '["배우1", "배우2"]'와 같은 형태이므로 각 값을 뽑아낸다.
# literal_evel : 문자열 그대로 파이썬 명령을 실행시켜주는 함수
# 예시---------------------------------------
# 문자열 : "['문자열1', '문자열2', 22, '33']"
# 리스트 : ['문자열1', '문자열2', 22, '33']
from ast import literal_eval

for idx, row in movie_final_분류.iterrows():
    # 개봉일 기준
    open = datetime.datetime.strftime(row['개봉일'], '%Y-%m-%d')
    # 해당 영화의 배우 확인
    this_actors = literal_eval(row['출연'])
    scores = [0] * len(this_actors)
    # 개봉일 이전 영화의 모든 배우 확인
    for i in range(len(this_actors)):
        actors = movie_resize_ranking.query(f'개봉일 < "{open}"')
        actors = actors.query(
            f'출연.str.contains("{this_actors[i]}")', engine='python')
        if len(actors) > 0:
            score = actors.index[0]
            if score >= 271:
                score = 1
            elif score >= 241:
                score = 2
            elif score >= 211:
                score = 3
            elif score >= 181:
                score = 4
            elif score >= 151:
                score = 5
            elif score >= 121:
                score = 6
            elif score >= 91:
                score = 7
            elif score >= 61:
                score = 8
            elif score >= 31:
                score = 9
            else:
                score = 10
            scores[i] = score

    # 평균/합/최대값 중에 잘 나오는 걸로        
    # 평균값
    # movie_final.loc[idx, '주연배우_흥행'] = round(sum(scores) / len(scores), 1)
    # 합
    movie_final_분류.loc[idx, '주연배우_흥행'] = sum(scores)
    # 최대값
    # movie_final.loc[idx, '주연배우_흥행'] = max(scores)

In [25]:
# 값 확인
print((movie_final_분류['감독_흥행'] == 0).value_counts())
print()
print((movie_final_분류['배급사_흥행'] == 0).value_counts())
print()
print((movie_final_분류['주연배우_흥행'] == 0).value_counts())

True     538
False    170
Name: 감독_흥행, dtype: int64

False    593
True     115
Name: 배급사_흥행, dtype: int64

False    506
True     202
Name: 주연배우_흥행, dtype: int64

### movie_final_ .csv 생성

In [26]:
movie_final_회귀.drop(['Unnamed: 0'],axis=1,inplace=True)
movie_final_분류.drop(['Unnamed: 0'],axis=1,inplace=True)

In [ ]:
# 변경 될때만 따로 풀어서 사용하시길.(파일생성코드)
movie_final_회귀.to_csv('./movie_final_reg.csv',encoding='utf-8')
movie_final_분류.to_csv('./movie_final_cls.csv',encoding='utf-8')